---
- name: Setup Nginx Reverse Proxy server on Ubuntu
  hosts: nginxrp
  become: yes
  vars:
    nginx_ssl_cert: "/etc/nginx/ssl/nginx-selfsigned.crt"
    nginx_ssl_key: "/etc/nginx/ssl/nginx-selfsigned.key"
    nginx_ssl_cert_src: "certs/nginx-selfsigned.crt"
    nginx_ssl_key_src: "certs/nginx-selfsigned.key"
    nginx_listen_ip: "192.168.99.100"
    nginx_listen_port: 80
    reverse_proxy_services:
      - name: syncthing
        server_name: syncthing.home.lab
        backend_protocol: http
        backend_host: 192.168.99.155
        backend_port: 8384
        enable_websocket: true
      - name: pihole
        server_name: pihole.home.lab
        backend_protocol: http
        backend_host: 192.168.99.120
        backend_port: 80
        enable_websocket: false
      - name: kasm
        server_name: kasm.home.lab
        backend_protocol: https
        backend_host: 192.168.99.110
        backend_port: 443
        enable_websocket: true
        custom_timeouts:
          read: 3600s
          send: 3600s
      - name: proxmox
        server_name: proxmox.home.lab
        backend_protocol: https
        enable_websocket: true
        enable_load_balancing: true
        backend_servers:
          - host: 192.168.99.211
            port: 8006
          - host: 192.168.99.212
            port: 8006
          - host: 192.168.99.213
            port: 8006
  
  tasks:
    - name: Create User Liam
      ansible.builtin.user:
        name: liam
        password: '$6$ucwTW4xk040GiZUs$QPoLpSkDeIgQgHGG1h3Gf2xKPiiNOeRkdsWpQUFMVYw2kTrJZYz0DL2BHXyedYi2e3X.zWYNOhc53WxGZ09qj.'
        groups: sudo
        shell: /bin/bash
        state: present

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - cloud-guest-utils   # for growpart
        state: present
        update_cache: yes

    - name: Create SSL directory
      ansible.builtin.file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: Copy SSL certificate
      ansible.builtin.copy:
        src: "{{ nginx_ssl_cert_src }}"
        dest: "{{ nginx_ssl_cert }}"
        owner: root
        group: root
        mode: '0644'
      notify: Reload NGINX

    - name: Copy SSL private key
      ansible.builtin.copy:
        src: "{{ nginx_ssl_key_src }}"
        dest: "{{ nginx_ssl_key }}"
        owner: root
        group: root
        mode: '0600'
      notify: Reload NGINX

    - name: Deploy NGINX reverse proxy configuration
      ansible.builtin.template:
        src: ../templates/reverse-proxy.conf.j2
        dest: /etc/nginx/conf.d/reverse-proxy.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload NGINX
      
    - name: Test nginx configuration
      command: nginx -t
      changed_when: false

    - name: Ensure NGINX service is enabled and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reload NGINX
      ansible.builtin.service:
        name: nginx
        state: reloaded
