---
- name: Create Nginx LXC Container
  hosts: localhost
  gather_facts: no
  
  vars:
    service_name: nginx
  
  tasks:
    - name: Create nginx LXC on Proxmox
      include_tasks: ../tasks/create-lxc.yml