---
- name: Create Pi-hole LXC Container
  hosts: localhost
  gather_facts: no
  
  vars:
    service_name: pihole
  
  tasks:
    - name: Create Pi-hole LXC on Proxmox
      include_tasks: ../tasks/create-lxc.yml