---
- name: Create Authelia LXC Container
  hosts: localhost
  gather_facts: no
  
  vars:
    proxmox_node: #########################
    proxmox_api_host: "192.168.99.210
    proxmox_api_user: "root@pam"

    vmid: 105
    hostname: authelia
    ip: 192.168.99.105
    gateway: 192.168.99.1
    subnet: 24
    nameserver: 192.168.99.120
    cores: 2
    memory: 2048
    disk: 8
    lxc_swap: 512
    lxc_disk: "8"
    lxc_storage: "local-lvm"
  
  tasks:
    - name: Create nginx LXC on Proxmox
      include_tasks: ../tasks/create-lxc.yml