---

# Pi-hole specific settings
pihole_dns_1: "1.1.1.1"              # or "208.67.222.222" (OpenDNS)
pihole_dns_2: "1.0.0.1"              # or "208.67.220.220" (OpenDNS)
pihole_listening_mode: "LOCAL"       # LOCAL, ALL, SINGLE, BIND
pihole_blocking_mode: "NULL"         # NULL, IP-NODATA-AAAA, IP, NXDOMAIN, NODATA
pihole_cache_size: 10000
pihole_max_db_days: 91
dns_domain: "lan"                    # or "home.lab"